- name: demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY  }}
    - name: task variable
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
      vars:
        URL_TASK: tasks.example.com

#store result of a task to OUTPUT variable
    - name: demo
      ansible.builtin.shell: uptime
      register: OUTPUT


#retrive the output variable
    - name: print OUTPUT of previous task
      ansible.builtin.debug:
        msg: "{{ OUTPUT }}"


  roles:
    - demo

#playlevel variable can be accessed by all the tasks
#tasklevel variables can accessed only by the task
#role level variable can be accessed in that role tasks
#varoiable from cli having higher precedence of any variable


#IMP if the value of any key is the variable the "" it
#ex: msg: {{url}} this needs to be given like this ex: msg"{{URL}}"