- name: Demo in template
  hosts: localhost
  tasks:
    - name: Copy example-copy.conf
      ansible.builtin.copy:
        src: example-copy.conf
        dest: /tmp/example-copy.conf

    - name: Template example-copy.conf
      ansible.builtin.template:
        src: example-copy.conf
        dest: /tmp/example-template-copy.conf

